apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flaskapp
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP